server:
  port: ${APP_PORT:8080}


app:
  mqtt:
    broker:
      url: ${MQTT_BROKER_URL}
      client_id: ${MQTT_CLIENT_ID}
      password: ${MQTT_PASSWORD}
  users:
    admin:
      email: ${ADMIN_EMAIL:admin@growtech.com}
      username: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin}
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXP_TIME}
    cors:
      allowed-origins: ${ALLOWED_ORIGINS}

spring:
  application:
    name: growtech-api

  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      database: ${MONGO_DATABASE}
      authentication-database: ${MONGO_AUTH_DATABASE}
      auto-index-creation: true

  config:
    import: optional:file:.env[.properties]

logging:
  file:
    name: "var/logs/application.log"
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        data: DEBUG