name: build sensors spring api image

on:
  push:
    branches: [main]

jobs:
  build-nodered:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Git Semantic Version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          major_pattern: "major:"
          minor_pattern: "feat:"
          patch_pattern: "fix:"
          format: "${major}.${minor}.${patch}-prerelease${increment}"
        id: version

      - name: Install buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Log in to the registry
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.DOCKER_REGISTRY}}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build sensors api docker image and push to the registry
        env:
          NEW_VERSION: ${{steps.version.outputs.version}}
          IMAGE_NAME: ${{ secrets.DOCKER_REGISTRY }}/sensors-api
        run: |
          docker buildx build --push \
            --tag ${{env.IMAGE_NAME}}:${{env.NEW_VERSION}} \
            --platform linux/amd64,linux/arm64 .
          docker buildx build --push \
            --tag ${{env.IMAGE_NAME}}:latest \
            --platform linux/amd64,linux/arm64 .
